# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Lego Toggle
email: brandonpoe@me.com
description: > # this means to ignore newlines until "baseurl:"
  A small javascript library to maintain state between elements.
baseurl: "/toggle" # the subpath of your site, e.g. /blog
url: "https://lego-js.github.io" # the base hostname & protocol for your site
twitter_username: btpoe
github_username:  btpoe

# Build settings
markdown: kramdown

stylus:
  compress: true
  path: ./_stylus